'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'

const statuses=['Submitted','More information needed','Review call requested','Property visit requested','Approved in principle','Not currently a fit','Onboarding agreement pending','Ready for publication']

export default function AdminPage(){
  const [unlocked,setUnlocked]=useState(false)
  const [password,setPassword]=useState('')
  const [items,setItems]=useState<any[]>([])
  const [selected,setSelected]=useState<any>(null)
  const [note,setNote]=useState('')
  useEffect(()=>{setUnlocked(sessionStorage.getItem('lhv-admin')==='ok');load()},[])
  function load(){try{const x=JSON.parse(localStorage.getItem('lhv-owner-submissions')||'[]');setItems(x);setSelected((s:any)=>s||x[0]||null)}catch{}}
  function login(){if(password===(process.env.NEXT_PUBLIC_LHV_ADMIN_PASSWORD||'LHV-REVIEW-2026')){sessionStorage.setItem('lhv-admin','ok');setUnlocked(true)}else alert('Incorrect password')}
  function changeStatus(newStatus:string){if(!selected)return;const updated={...selected,status:newStatus,history:[...(selected.history||[]),{timestamp:new Date().toISOString(),reviewer:'Little Hut reviewer',previousStatus:selected.status||'Submitted',newStatus,note}]};const next=items.map(x=>x.reference===updated.reference?updated:x);localStorage.setItem('lhv-owner-submissions',JSON.stringify(next));setItems(next);setSelected(updated);setNote('')}
  if(!unlocked)return <main className="page-shell"><section className="wizard"><p className="eyebrow">PRIVATE REVIEW AREA</p><h1>Little Hut admin</h1><p>This Phase 1 console is password-gated and reads submissions stored in this browser only.</p><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button className="button full" onClick={login}>Open review area</button></section></main>
  return <main className="page-shell"><div className="page-head"><Link className="brand" href="/"><span className="brand-mark">⌂</span><span>LITTLE HUT<small>VACATIONS</small></span></Link><button className="text-link" onClick={()=>{sessionStorage.removeItem('lhv-admin');setUnlocked(false)}}>Lock</button></div><section className="section-intro"><p className="eyebrow">PRIVATE ADMIN REVIEW</p><h2>Property submissions</h2><p>Temporary Phase 1 browser storage. No public property publication is automated.</p></section><div className="admin-grid"><aside className="submission-list">{items.length===0?<p className="muted">No submissions in this browser.</p>:items.map(item=><button className="submission-item" key={item.reference} onClick={()=>setSelected(item)}><strong>{item.propertyName||'Unnamed property'}</strong><br/><small>{item.reference} · {item.status}</small></button>)}</aside><section className="submission-detail">{selected&&<><div className="page-head"><div><h2>{selected.propertyName||'Unnamed property'}</h2><p>{selected.reference}</p></div><span className="status-badge">{selected.status}</span></div><h3>Owner details</h3><p>{selected.fullName}<br/>{selected.mobile}<br/>{selected.email}</p><h3>Property summary</h3><p>{selected.unitType} · {selected.compound} · {selected.area}<br/>{selected.bedrooms} bedrooms · {selected.bathrooms} bathrooms · claimed capacity {selected.capacity}</p><h3>Amenities requiring verification</h3><p>{(selected.features||[]).join(', ')||'None selected'}</p><h3>Operating setup</h3><p>Preparation: {selected.preparation}<br/>Guest support: {selected.guestSupport}<br/>Access: {selected.accessMethod}<br/>Check-in/out: {selected.checkIn} / {selected.checkOut}</p><h3>Commercial expectations</h3><p>Owner-entered rate: {selected.nightlyRate||'Not provided'}<br/>Minimum stay: {selected.minimumStay}<br/>Availability: {selected.availability}</p><h3>External listing</h3><p>{selected.listingLink?<a className="text-link" href={selected.listingLink} target="_blank" rel="noreferrer">Open listing</a>:'None provided'}</p><label>Internal note<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} /></label><label>Review status<select value={selected.status} onChange={e=>changeStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><h3>Status history</h3><ul>{(selected.history||[]).map((h:any,i:number)=><li key={i}>{new Date(h.timestamp).toLocaleString()} — {h.reviewer}: {h.previousStatus} → {h.newStatus}{h.note?` — ${h.note}`:''}</li>)}</ul></>}</section></div></main>
}
